version: "2"
services:
  influxdb:
    container_name: influxdb
    image: influxdb:1.8.3
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - /home/core/volumes/influxdb:/var/lib/influxdb
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana:6.6
    ports:
      - "3000:3000"
    links:
      - influxdb
    restart: always

  telegraf:
    container_name: telegraf
    image: telegraf:1.16.0
    network_mode: "host"
    volumes:
      - /home/core/conf/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
